name: wallet_apps
description: A new Flutter project. 

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 5.0.3+84
#6 feature
#8 debug
#1 refactor
#last 8 build
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

# parts:
#   uet-lms:
#     source: .
#     plugin: flutter
#     flutter-target: lib/main.dart
#     build-packages:
#       - libsecret-1-dev
#       - libjsoncpp-dev
#     stage-packages:
#       - libsecret-1-dev
#       - libjsoncpp-dev
      
dependencies:
  cupertino_icons:
  
  flutter:
    sdk: flutter
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  # Icons
  iconsax: ^0.0.8

  # silder
  carousel_slider: ^4.1.1 
  smooth_page_indicator: ^1.0.0+2
  flutter_slidable: ^1.3.0

  geolocator:
  geocoding:

  gsheets:
  
  # Storage
  get_storage: 
  shared_preferences:

  # Backend
  http: 
  connectivity_plus:
  async:

  # Image service
  intl:

  ######## Permission Package ########
  # Camera
  qr_flutter: 
  qr_code_scanner: ^1.0.0

  # Chart
  fl_chart: ^0.46.0
  pie_chart:

  # Icons
  line_awesome_flutter:
  pinput:
  date_format:
 
  store_redirect:
  share:

  vibration: ^1.7.4-nullsafety.0
 
  # Apps Configuration
  rename:
  package_info: 
  shimmer:

  # Authentication & Verification
  local_auth:
  web_socket_channel:
    # path: ../
  animations:
  provider:
  web3dart: 
  bip39:

  dart_ecpair:
  defichaindart:

  flutter_secure_storage:
  flutter_screenshot_switcher:

  #Contact
  fluttercontactpicker: ^4.7.0
  
  #animation
  flare_flutter:
  responsive_framework:
  flutter_launcher_icons:
  url_launcher:
  loading_indicator:
  fluttertoast:
  in_app_update:
  tutorial_coach_mark:
  transition: ^2.0.2
  lottie: ^1.3.0
  motion_toast:

  # flutter lock passcode
  flutter_screen_lock: ^5.0.12
  ai_progress: ^2.0.0
  responsive_sizer: ^3.0.8

  # Third-party
  wallet_connect:
  eth_sig_util: ^0.0.7
  
  # webview_flutter
  flutter_inappwebview: ^5.4.3+7

  # Device Preview
  device_preview: ^1.1.0

  flutter_native_splash: ^2.2.3
  mobile_scanner: ^2.0.0
  random_avatar: 
  # Download
  # path_provider:
  # downloads_path_provider_28:
  
dependency_overrides:
    # git:
    #   url: https://github.com/polkawallet-io/ui.git
    #   ref: 485a9cde97f2446d74a1aeb6d8d63e33683461a5
    
  polkawallet_sdk:
  flutter_svg:
  bip32_defichain:
  charts_flutter:
     git:
       url: https://github.com/google/charts
       path: charts_flutter

  permission_handler: ^10.0.0
  # get_storage:
  # flutter_aes_ecb_pkcs5:

dev_dependencies:
  flutter_test:
    sdk: flutter

# run: flutter clean && flutter pub get && flutter pub run flutter_native_splash:create
flutter_native_splash: 
  color: "#023859"
  
  image: assets/logo/bitriel-splash.png
  android: true
  android12: false
  ios: true
 

# Run command: flutter pub run flutter_launcher_icons:main 
flutter_icons:
  image_path: "assets/logo/bitriel_icon.png"
  ios: true
  android: true


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - assets/
    - assets/github/
    - assets/abi/
    - assets/icons/
    - assets/token_logo/
    - assets/json/
    - assets/logo/
    - assets/ads/
    - assets/illustration/

    # - ../assets/
    # - ../assets/github/
    # - ../assets/abi/
    # - ../assets/icons/
    # - ../assets/token_logo/
    # - ../assets/json/
    # - ../assets/logo/
    # - ../assets/illustration/
    
    # Animation Flare
    - assets/animation/
    - lib/src/js_api/
    - lib/src/js_api/dist/main.js

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
    - family: Avenir
      fonts:
        - asset: assets/fonts/avenir_ff/AvenirLTStd-Roman.otf
        
  uses-material-design: true
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  #module: 
   # androidX: true